source 'https://rubygems.org'

gem 'activerecord'
gem 'activesupport'
gem 'bigdecimal'
gem 'byebug'
gem 'faraday'
gem 'pg'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'simplecov'
gem 'standalone_migrations'
gem 'terminal-table'
